; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
monitor_port = COM5
upload_port = COM5
build_src_filter = +<*> -<esp32_ac_main.cpp> -<esp32_GCS_main.cpp>

[env:seeed_xiao_esp32c3_AC]
platform = espressif32
board = seeed_xiao_esp32c3
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
framework = arduino
monitor_speed = 115200
monitor_port = COM6
upload_port = COM6
build_src_filter = +<esp32_ac_main.cpp> +<data_structs.h> +<config.h> +<config.cpp>

[env:seeed_xiao_esp32c3_GCS]
platform = espressif32
board = seeed_xiao_esp32c3
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
framework = arduino
monitor_speed = 115200
monitor_port = COM7
upload_port = COM7
build_src_filter = +<esp32_GCS_main.cpp> +<data_structs.h> +<config.h> +<config.cpp>